proxy-providers:
  proxy:
    type: http
    url: "url"
    interval: 3600
    path: ./proxy.yaml
    filter: '*' # golang regex 正则表达式
    health-check:
      enable: true
      interval: 300
      # lazy: true
      url: http://www.gstatic.com/generate_204
  OPENAI:
    type: http
    url: "url"
    interval: 3600
    path: ./OPENAI.yaml
    filter: '日本|美国' # golang regex 正则表达式
    health-check:
      enable: true
      interval: 300
      # lazy: true
      url: http://www.gstatic.com/generate_204      

rule-providers:
  reject: # 广告域名列表
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400
  googledrive: # 
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GoogleDrive/GoogleDrive.yaml"
    path: ./ruleset/googledrive.yaml
    interval: 86400

  googlesearch: # 
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GoogleSearch/GoogleSearch.yaml"
    path: ./ruleset/googlesearch.yaml
    interval: 86400

  proxy: # 代理域名列表
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  cncidr: # 中国大陆 IP 地址列表
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400
    
  lancidr: # 局域网 IP 及保留 IP 地址列表
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400 

rules:
  - DOMAIN-SUFFIX,bdiso.net,proxy
  - RULE-SET,reject,REJECT
  - RULE-SET,googledrive,proxy
  - RULE-SET,googlesearch,proxy
  - RULE-SET,proxy,proxy
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,lancidr,DIRECT
  - GEOIP,,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH, DIRECT       
